name: codecov

on:
  push:
    branches: [ "main" ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage/reports/
          fail_ci_if_error: true
          files: ./coverage/clover.xml
          name: carcassonne-map-generator-coverage
          path_to_write_report: ./coverage/coverage-final.json
          verbose: true
